<?php
/**
 * @license http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @author Didier Berlioz <berliozd@gmail.com>
 * @copyright Copyright (c) 2019 Addeos (http://www.addeos.com)
 */

/** @var \Addeos\ReqRes\Block\ColorsAgain $block */
?>

<h1><?php echo __('Colors in a second block'); ?></h1>
<ul>
    <?php foreach ($block->getColorNames() as $colorName): ?>
        <li><?php echo __('Color "%1"', $colorName); ?></li>
    <?php endforeach; ?>
</ul>
