<?php
/**
 * @license http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @author Didier Berlioz <berliozd@gmail.com>
 * @copyright Copyright (c) 2019 Addeos (http://www.addeos.com)
 */

/** @var \Addeos\ReqRes\Block\Colors $block */
?>

<h1><?php echo __('Colors in a first block'); ?></h1>
<ul>
    <?php
    /** @var \Addeos\ReqRes\Model\Color $color */
    foreach ($block->getColors() as $color): ?>
        <li><?php echo __('Color "%1"', $color->getName()); ?></li>
    <?php endforeach; ?>
</ul>
